# Generated by Django 4.1.5 on 2023-08-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='cook',
        ),
    ]
