# Generated by Django 4.1.5 on 2023-08-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_author_post_cook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cook',
            new_name='author',
        ),
    ]
